### ISSUE TITLE
Bilder Fehler

### ISSUE THREAD

**Issue by Valle137m** [creative-lighthouse/halloweenhaus-website#1]
Einige Bilder werden nicht angezeigt. Ich hatte die z.B. bei den Charakteren hochgeladen. Unter "choose existing" sieht man die fehlerhaften Uploads. Hier wird die Fehlermeldung "The string did not match the expected pattern." angezeigt.

**Comment by StevenPaw** [comment]
Should be fixed with d0fa0d2b7a7a54ad5cbd9043e37db21f6bc9ffa7
