### ISSUE TITLE
Fix charakter movement on history-Slider

### ISSUE THREAD

**Issue by zwibblTV** [creative-lighthouse/halloweenhaus-website#3]
Auf der Geschichte-Seite gibt es oben den Slider mit dem ganzen Charakteren. Wenn man nach unten scrollt, dann bewegen die Charaktere sich mit, was vor allem auf dem Handy total doof aussieht

**Comment by StevenPaw** [comment]
Changed with 515f79d37fbc31e1c910c7d065f323db77c58892
